### ISSUE TITLE
De-duplicate header

### ISSUE THREAD

**Issue by volodymyr-kushnir** [oladushkas/lesson#21]
Some blocks are repeated twice. Let's get rid of one of them.

**Comment by oladushkas** [comment]
So far found three cases of look-alike titles (not duplicate though, as following in italics):
 - Game Designer / Artist at _Wroclaw / Krakow_ Game Jam
 -  Product Manager, Marketing at Garage 48 _Dnipro IoT / Odessa Gamification_ Hackathon
 -  2nd place in _Sociology / PR_ nomination at the TNS Youth Studies Marketing competition

I am going to shift from stilted official formulations to more lively (and short!) titles and descriptions through the whole text. Supposedly that would reduce similitude, what do you think?

**Comment by volodymyr-kushnir** [comment]
You misunderstood the task. https://oladushkas.github.io/lesson/ It clearly has "Daria Korotkih" twice.
