### ISSUE TITLE
Suspicious markup for "Office Manager at Orange Travel LLC"

### ISSUE THREAD

**Issue by volodymyr-kushnir** [oladushkas/lesson#25]
Seems like "Office Manager at Orange Travel LLC" block has a suspicious markup — "WORK" tag is thrown onto a separate line, which is kinda odd. Let's double-check that.

**Comment by volodymyr-kushnir** [comment]
"Regarding"? Okay, next time choose a keyword from this list https://help.github.com/articles/closing-issues-using-keywords/

**Comment by oladushkas** [comment]
Sorry, should have mentioned I used that word deliberately. I wanted to reference the issue but wasn't sure it is entirely solved until I test it on office desktop.
Thanks for the list anyway, I was aware of less than half of it.
