### ISSUE TITLE
What's left to do?

### ISSUE THREAD

**Issue by volodymyr-kushnir** [oladushkas/lesson#9]
# TODO:

##### Set up
 - Create new GitHub acc
 - Create repo Homepage, project Resume
 - Define tags to use

#### Reimagine positioning of the blocks (https://dribbble.com/search?q=resume)
   - gather best features and bookmark

#### Add missing blocks content:
   - <s>contacts (phone number, mail, facebook/skype?)</s>
   - languages
   - skills
   - <s>list of events I made through last year</s>
   - references
   - social bar

#### Update texts
   - change lorem ipsums
   - work on about (statment)
   - enhance with links
   - go with Ed through it

#### Work on interface
   - change fonts
   - add graphic elements (socials, divider, etc.)
   - add border

**Comment by oladushkas** [comment]
Am I not supposed to write in separate issues to make cards out of every bulletpoint?

**Comment by volodymyr-kushnir** [comment]
You are, but todo list is not yet compiled so it's an issue of its own. Therefore it lands here as a separate topic open for discussion.
